### ISSUE TITLE
PermissionError using download_raw_data

### ISSUE THREAD

**Issue by nick-gorman** [UNSW-CEEM/NEMSEER#6] opened 2022-08-17 00:23 UTC
Running the example code below on a windows machine leads to a permission error.

Example:

```python
import nemseer
nemseer.download_raw_data(
    forecast_start = "01/01/2020 00:00", 
    forecast_end = "02/01/2020 00:00",
    forecasted_start = "02/01/2020 00:00",
    forecasted_end = "02/01/2020 00:00",
    forecast_type = "P5MIN",
    tables = "REGIONSOLUTION",
    raw_cache = "/my/raw/cache/",
    keep_csv = False
)
```

Error:

```
INFO: Created directory at C:\cache
INFO: Downloading and unzipping REGIONSOLUTION for 1/2020
PUBLIC_DVD_P5MIN_REGIONSOLUTION_202001010000.zip: 100%|██████████| 32.9M/32.9M [00:09<00:00, 3.70MB/s]
Traceback (most recent call last):
  File "C:/Users/nick/PycharmProjects/nemseer_test/main.py", line 2, in <module>
    nemseer.download_raw_data(
  File "C:\Users\nick\PycharmProjects\nemseer_test\venv\lib\site-packages\nemseer\nemseer.py", line 46, in download_raw_data
    downloader.download_csv()
  File "C:\Users\nick\PycharmProjects\nemseer_test\venv\lib\site-packages\nemseer\downloader.py", line 362, in download_csv
    get_unzipped_csv(url, self.raw_cache)
  File "C:\Users\nick\PycharmProjects\nemseer_test\venv\lib\site-packages\nemseer\downloader.py", line 296, in get_unzipped_csv
    Path(file_path).unlink()
  File "C:\Users\nick\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1324, in unlink
    self._accessor.unlink(self)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '\\cache\\PUBLIC_DVD_P5MIN_REGIONSOLUTION_202001010000.zip'

Process finished with exit code 1
```

**Comment by prakaa** [comment] 2022-08-18 00:16
Thanks @nick-gorman. Reproduced this error on Windows - seems to be the case that Linux/macOS work fine without calling `Zipfile.close()`, but Windows needs this call. 

This has been resolved via 7d44099fee27ecbf5a7ccd8d2ef6965d0b14512b and will be rolled into v0.2.1

**Closed by prakaa** 2022-08-18 00:16 UTC
Labels: bug
